version: "3"
services:
  nodejs:
    image: ozgencdev/sso-2
    container_name: nodejs
    ports:
      - "3005:3010"
  react:
    image: ozgencdev/dockreact
    container_name: react
    ports:
      - "3000"
